import React, { useState, useMemo } from 'react';
import { useLanguage } from '../../i18n';
import { useApp } from '../../context/AppContext';
import { formatCurrency } from '../../utils/currencyUtils';
import { MONTH_NAMES_EN, MONTH_NAMES_GU } from '../../utils/dateUtils';
import { downloadFullRentalReportPDF } from '../../utils/pdfUtils';
import { getWhatsAppShareUrl } from '../../utils/receiptUtils';
import { StatusBadge } from '../common/StatusBadge';
import {
  FileText,
  Printer,
  Download,
  Share2,
  Calendar,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  AlertCircle,
  CheckCircle2,
  Users
} from 'lucide-react';

interface MonthlyReportViewProps {
  onClose?: () => void;
}

export const MonthlyReportView: React.FC<MonthlyReportViewProps> = ({ onClose }) => {
  const { t, language } = useLanguage();
  const { tenants, payments, metrics } = useApp();

  const today = new Date();
  const [selectedYear, setSelectedYear] = useState<number>(today.getFullYear());
  const [selectedMonthIndex, setSelectedMonthIndex] = useState<number>(today.getMonth());

  const monthKey = `${selectedYear}-${String(selectedMonthIndex + 1).padStart(2, '0')}`;
  const monthLabel = `${language === 'gu' ? MONTH_NAMES_GU[selectedMonthIndex] : MONTH_NAMES_EN[selectedMonthIndex]} ${selectedYear}`;

  const handlePrevMonth = () => {
    if (selectedMonthIndex === 0) {
      setSelectedMonthIndex(11);
      setSelectedYear((prev) => prev - 1);
    } else {
      setSelectedMonthIndex((prev) => prev - 1);
    }
  };

  const handleNextMonth = () => {
    if (selectedMonthIndex === 11) {
      setSelectedMonthIndex(0);
      setSelectedYear((prev) => prev + 1);
    } else {
      setSelectedMonthIndex((prev) => prev + 1);
    }
  };

  // Active tenants calculation for the chosen period
  const activeTenants = useMemo(() => {
    return tenants.filter((t) => !t.isArchived);
  }, [tenants]);

  // Tenant breakdown for chosen month
  const reportData = useMemo(() => {
    let totalDemand = 0;
    let totalCollected = 0;

    const rows = activeTenants.map((tenant) => {
      // Find stay active during this month or current rent
      const activeStay = tenant.stays?.find((s) => s.isActive) || tenant.stays?.[tenant.stays.length - 1];
      const rentDemand = activeStay?.monthlyRent || tenant.monthlyRent || 0;

      // Payments made for this specific billing month
      const monthPayments = payments.filter(
        (p) => p.tenantId === tenant.id && (p.billingMonth === monthKey || (!p.billingMonth && p.paymentDate.startsWith(monthKey)))
      );
      const paid = monthPayments.reduce((sum, p) => sum + p.amountPaid, 0);
      const pending = Math.max(0, rentDemand - paid);

      totalDemand += rentDemand;
      totalCollected += paid;

      let status: 'paid' | 'partial' | 'pending' | 'overdue' = 'pending';
      if (paid >= rentDemand && rentDemand > 0) {
        status = 'paid';
      } else if (paid > 0) {
        status = 'partial';
      } else {
        // Check if overdue relative to today if in current or past month
        status = 'pending';
      }

      return {
        tenant,
        rentDemand,
        paid,
        pending,
        status,
        paymentCount: monthPayments.length
      };
    });

    const totalPending = Math.max(0, totalDemand - totalCollected);
    const collectionRate = totalDemand > 0 ? Math.round((totalCollected / totalDemand) * 100) : 0;

    return {
      rows,
      totalDemand,
      totalCollected,
      totalPending,
      collectionRate
    };
  }, [activeTenants, payments, monthKey]);

  // WhatsApp share message
  const handleShareWhatsApp = () => {
    const text = `📊 *RENTAL REPORT - ${monthLabel.toUpperCase()}*
━━━━━━━━━━━━━━━━━━
🏢 *Active Tenants:* ${activeTenants.length}
💰 *Total Rent Demand:* ₹${reportData.totalDemand.toLocaleString('en-IN')}
✅ *Total Collected:* ₹${reportData.totalCollected.toLocaleString('en-IN')} (${reportData.collectionRate}%)
⚠️ *Total Pending:* ₹${reportData.totalPending.toLocaleString('en-IN')}
━━━━━━━━━━━━━━━━━━
*Pending Summary:*
${reportData.rows
  .filter((r) => r.pending > 0)
  .map((r) => `• ${r.tenant.name} (${r.tenant.tenantCode || 'TEN-0000'} | Rm #${r.tenant.roomNumber}): ₹${r.pending.toLocaleString('en-IN')} pending`)
  .join('\n') || 'All rents cleared! 🎉'}

_Generated by RentManager App_`;

    const url = getWhatsAppShareUrl('', text);
    window.open(url, '_blank');
  };

  return (
    <div className="space-y-4 pb-20 pt-2 animate-fade-in">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h2 className="font-extrabold text-xl text-slate-900 tracking-tight flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            <span>{language === 'gu' ? 'માસિક નાણાકીય અહેવાલ' : 'Monthly Financial Report'}</span>
          </h2>
          <p className="text-xs text-slate-500">
            {language === 'gu' ? 'મહિના મુજબ ભાડું આવક અને બાકી વિશ્લેષણ' : 'Monthly demand, collections, and pending dues ledger'}
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          <button
            onClick={handleShareWhatsApp}
            className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-md shadow-emerald-500/20 transition-all active:scale-95"
            title="Share via WhatsApp"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => downloadFullRentalReportPDF(tenants, payments, metrics, language)}
            className="flex items-center gap-1.5 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md shadow-blue-500/20 transition-all active:scale-95"
            title="Download PDF"
          >
            <Download className="w-3.5 h-3.5" />
            <span>PDF</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-2 border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 rounded-xl text-xs font-bold transition-all"
            title="Print Report"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>{language === 'gu' ? 'પ્રિન્ટ' : 'Print'}</span>
          </button>
        </div>
      </div>

      {/* Month Navigator */}
      <div className="bg-white rounded-2xl p-3 border border-slate-200 shadow-card flex items-center justify-between">
        <button
          onClick={handlePrevMonth}
          className="p-2 rounded-xl hover:bg-slate-100 text-slate-600 transition-colors"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>

        <div className="text-center">
          <div className="flex items-center justify-center gap-2 font-extrabold text-base text-slate-900">
            <Calendar className="w-4 h-4 text-blue-600" />
            <span>{monthLabel}</span>
          </div>
          <span className="text-[11px] text-slate-500 font-medium">
            {reportData.rows.length} {language === 'gu' ? 'ભાડુઆતો' : 'tenants evaluated'}
          </span>
        </div>

        <button
          onClick={handleNextMonth}
          className="p-2 rounded-xl hover:bg-slate-100 text-slate-600 transition-colors"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'કુલ અપેક્ષિત ભાડું' : 'Total Rent Demand'}
          </span>
          <div className="font-extrabold text-lg text-slate-900 mt-1">
            {formatCurrency(reportData.totalDemand)}
          </div>
          <span className="text-[10px] text-slate-500">100% Demand</span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'કુલ જમા થયેલ' : 'Total Collected'}
          </span>
          <div className="font-extrabold text-lg text-emerald-600 mt-1">
            {formatCurrency(reportData.totalCollected)}
          </div>
          <span className="text-[10px] font-bold text-emerald-600">
            {reportData.collectionRate}% Collected
          </span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'કુલ બાકી ભાડું' : 'Total Pending'}
          </span>
          <div className="font-extrabold text-lg text-rose-600 mt-1">
            {formatCurrency(reportData.totalPending)}
          </div>
          <span className="text-[10px] text-rose-500 font-bold">
            {100 - reportData.collectionRate}% Remaining
          </span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'વસૂલાત દર' : 'Collection Rate'}
          </span>
          <div className="font-extrabold text-lg text-blue-600 mt-1">
            {reportData.collectionRate}%
          </div>
          {/* Progress mini bar */}
          <div className="w-full h-1.5 bg-slate-100 rounded-full mt-2 overflow-hidden">
            <div
              className={`h-full transition-all duration-500 ${
                reportData.collectionRate >= 80 ? 'bg-emerald-500' : reportData.collectionRate >= 50 ? 'bg-amber-500' : 'bg-rose-500'
              }`}
              style={{ width: `${reportData.collectionRate}%` }}
            />
          </div>
        </div>
      </div>

      {/* Tenant Breakdown Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-card overflow-hidden">
        <div className="p-4 border-b border-slate-100 flex items-center justify-between">
          <h3 className="font-extrabold text-sm text-slate-900 flex items-center gap-2">
            <Users className="w-4 h-4 text-slate-500" />
            <span>{language === 'gu' ? 'ભાડુઆત મુજબ વિગત' : 'Tenant Breakdown Ledger'}</span>
          </h3>
          <span className="text-xs text-slate-500 font-bold">
            {reportData.rows.filter((r) => r.status === 'paid').length} / {reportData.rows.length} {language === 'gu' ? 'પૂર્ણ' : 'Paid'}
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-slate-600 font-bold uppercase tracking-wider text-[10px]">
                <th className="py-3 px-4">{language === 'gu' ? 'ભાડુઆત' : 'Tenant'}</th>
                <th className="py-3 px-3">{language === 'gu' ? 'રૂમ' : 'Room'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'અપેક્ષિત' : 'Expected'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'ચૂકવેલ' : 'Paid'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'બાકી' : 'Pending'}</th>
                <th className="py-3 px-4 text-center">{language === 'gu' ? 'સ્થિતિ' : 'Status'}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {reportData.rows.map(({ tenant, rentDemand, paid, pending, status }) => (
                <tr key={tenant.id} className="hover:bg-slate-50/80 transition-colors">
                  <td className="py-3 px-4">
                    <div className="font-bold text-slate-900">{tenant.name}</div>
                    <div className="flex items-center gap-1.5 text-[10px] text-slate-400">
                      <span className="font-mono text-blue-700">{tenant.tenantCode || 'TEN-0000'}</span>
                      <span>•</span>
                      <span>{tenant.mobile}</span>
                    </div>
                  </td>
                  <td className="py-3 px-3">
                    <span className="font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                      #{tenant.roomNumber}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-right font-medium text-slate-800">
                    {formatCurrency(rentDemand)}
                  </td>
                  <td className="py-3 px-3 text-right font-bold text-emerald-600">
                    {formatCurrency(paid)}
                  </td>
                  <td className="py-3 px-3 text-right font-bold text-rose-600">
                    {formatCurrency(pending)}
                  </td>
                  <td className="py-3 px-4 text-center">
                    <StatusBadge status={status} />
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="bg-slate-50 font-extrabold text-slate-900 border-t-2 border-slate-200">
                <td className="py-3 px-4" colSpan={2}>
                  {language === 'gu' ? 'કુલ સરવાળો' : 'Total'}
                </td>
                <td className="py-3 px-3 text-right">{formatCurrency(reportData.totalDemand)}</td>
                <td className="py-3 px-3 text-right text-emerald-600">{formatCurrency(reportData.totalCollected)}</td>
                <td className="py-3 px-3 text-right text-rose-600">{formatCurrency(reportData.totalPending)}</td>
                <td className="py-3 px-4 text-center text-blue-600">{reportData.collectionRate}%</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  );
};
