import React, { useState, useMemo } from 'react';
import { useLanguage } from '../../i18n';
import { useApp } from '../../context/AppContext';
import { formatCurrency } from '../../utils/currencyUtils';
import { MONTH_NAMES_EN, MONTH_NAMES_GU } from '../../utils/dateUtils';
import { downloadFullRentalReportPDF } from '../../utils/pdfUtils';
import { getWhatsAppShareUrl } from '../../utils/receiptUtils';
import {
  TrendingUp,
  Printer,
  Download,
  Share2,
  Calendar,
  ChevronLeft,
  ChevronRight,
  BarChart3,
  DollarSign
} from 'lucide-react';

interface YearlyReportViewProps {
  onSelectMonth?: (year: number, monthIndex: number) => void;
}

export const YearlyReportView: React.FC<YearlyReportViewProps> = ({ onSelectMonth }) => {
  const { t, language } = useLanguage();
  const { tenants, payments, metrics } = useApp();

  const currentYear = new Date().getFullYear();
  const [selectedYear, setSelectedYear] = useState<number>(currentYear);

  const activeTenants = useMemo(() => {
    return tenants.filter((t) => !t.isArchived);
  }, [tenants]);

  // Aggregate monthly data for the 12 months of selectedYear
  const yearlyData = useMemo(() => {
    let yearTotalDemand = 0;
    let yearTotalCollected = 0;

    const months = Array.from({ length: 12 }, (_, monthIndex) => {
      const monthKey = `${selectedYear}-${String(monthIndex + 1).padStart(2, '0')}`;
      const monthLabel = language === 'gu' ? MONTH_NAMES_GU[monthIndex] : MONTH_NAMES_EN[monthIndex];

      // Calculate demand for active tenants in this month
      // For accurate demand, sum active tenants monthlyRent
      const demand = activeTenants.reduce((sum, tenant) => {
        const activeStay = tenant.stays?.find((s) => s.isActive) || tenant.stays?.[tenant.stays.length - 1];
        return sum + (activeStay?.monthlyRent || tenant.monthlyRent || 0);
      }, 0);

      // Sum payments for this month
      const collected = payments
        .filter((p) => p.billingMonth === monthKey || (!p.billingMonth && p.paymentDate.startsWith(monthKey)))
        .reduce((sum, p) => sum + p.amountPaid, 0);

      const pending = Math.max(0, demand - collected);
      const collectionRate = demand > 0 ? Math.min(100, Math.round((collected / demand) * 100)) : 0;

      yearTotalDemand += demand;
      yearTotalCollected += collected;

      return {
        monthIndex,
        monthKey,
        monthLabel,
        demand,
        collected,
        pending,
        collectionRate
      };
    });

    const yearTotalPending = Math.max(0, yearTotalDemand - yearTotalCollected);
    const yearCollectionRate = yearTotalDemand > 0 ? Math.round((yearTotalCollected / yearTotalDemand) * 100) : 0;

    // Max amount for SVG chart scaling
    const maxVal = Math.max(1, ...months.map((m) => Math.max(m.demand, m.collected)));

    return {
      months,
      yearTotalDemand,
      yearTotalCollected,
      yearTotalPending,
      yearCollectionRate,
      maxVal
    };
  }, [selectedYear, activeTenants, payments, language]);

  const handleShareWhatsApp = () => {
    const text = `📈 *ANNUAL FINANCIAL REPORT - ${selectedYear}*
━━━━━━━━━━━━━━━━━━
💰 *Annual Expected Demand:* ₹${yearlyData.yearTotalDemand.toLocaleString('en-IN')}
✅ *Annual Collected:* ₹${yearlyData.yearTotalCollected.toLocaleString('en-IN')} (${yearlyData.yearCollectionRate}%)
⚠️ *Annual Total Pending:* ₹${yearlyData.yearTotalPending.toLocaleString('en-IN')}
━━━━━━━━━━━━━━━━━━
*Top Monthly Highlights:*
${yearlyData.months
  .filter((m) => m.collected > 0)
  .slice(-4)
  .map((m) => `• ${m.monthLabel}: ₹${m.collected.toLocaleString('en-IN')} (${m.collectionRate}%)`)
  .join('\n')}

_Generated by RentManager App_`;

    const url = getWhatsAppShareUrl('', text);
    window.open(url, '_blank');
  };

  return (
    <div className="space-y-4 pb-20 pt-2 animate-fade-in">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h2 className="font-extrabold text-xl text-slate-900 tracking-tight flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-indigo-600" />
            <span>{language === 'gu' ? 'વાર્ષિક નાણાકીય અહેવાલ' : 'Yearly Financial Report'}</span>
          </h2>
          <p className="text-xs text-slate-500">
            {language === 'gu' ? 'વાર્ષિક ભાડું વસૂલાત વિશ્લેષણ અને વૃદ્ધિ ગ્રાફ' : '12-Month rental collection trends and annual collection efficiency'}
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          <button
            onClick={handleShareWhatsApp}
            className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-md shadow-emerald-500/20 transition-all active:scale-95"
            title="Share via WhatsApp"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => downloadFullRentalReportPDF(tenants, payments, metrics, language)}
            className="flex items-center gap-1.5 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md shadow-blue-500/20 transition-all active:scale-95"
            title="Download PDF"
          >
            <Download className="w-3.5 h-3.5" />
            <span>PDF</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-2 border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 rounded-xl text-xs font-bold transition-all"
            title="Print Report"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>{language === 'gu' ? 'પ્રિન્ટ' : 'Print'}</span>
          </button>
        </div>
      </div>

      {/* Year Navigator */}
      <div className="bg-white rounded-2xl p-3 border border-slate-200 shadow-card flex items-center justify-between">
        <button
          onClick={() => setSelectedYear((y) => y - 1)}
          className="p-2 rounded-xl hover:bg-slate-100 text-slate-600 transition-colors"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>

        <div className="text-center">
          <div className="flex items-center justify-center gap-2 font-black text-xl text-slate-900">
            <Calendar className="w-5 h-5 text-indigo-600" />
            <span>{selectedYear}</span>
          </div>
          <span className="text-[11px] text-slate-500 font-medium">
            {language === 'gu' ? 'નાણાકીય કેલેન્ડર વર્ષ' : 'Calendar Year Overview'}
          </span>
        </div>

        <button
          onClick={() => setSelectedYear((y) => y + 1)}
          className="p-2 rounded-xl hover:bg-slate-100 text-slate-600 transition-colors"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'વાર્ષિક અપેક્ષિત ભાડું' : 'Yearly Demand'}
          </span>
          <div className="font-extrabold text-lg text-slate-900 mt-1">
            {formatCurrency(yearlyData.yearTotalDemand)}
          </div>
          <span className="text-[10px] text-slate-500">12 Months Expected</span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'વાર્ષિક વસૂલ ભાડું' : 'Yearly Collected'}
          </span>
          <div className="font-extrabold text-lg text-emerald-600 mt-1">
            {formatCurrency(yearlyData.yearTotalCollected)}
          </div>
          <span className="text-[10px] font-bold text-emerald-600">
            {yearlyData.yearCollectionRate}% Total
          </span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'વાર્ષિક કુલ બાકી' : 'Yearly Pending'}
          </span>
          <div className="font-extrabold text-lg text-rose-600 mt-1">
            {formatCurrency(yearlyData.yearTotalPending)}
          </div>
          <span className="text-[10px] text-rose-500 font-bold">
            {100 - yearlyData.yearCollectionRate}% Outstanding
          </span>
        </div>

        <div className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-card">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            {language === 'gu' ? 'વાર્ષિક વસૂલાત દર' : 'Annual Efficiency'}
          </span>
          <div className="font-extrabold text-lg text-indigo-600 mt-1">
            {yearlyData.yearCollectionRate}%
          </div>
          <div className="w-full h-1.5 bg-slate-100 rounded-full mt-2 overflow-hidden">
            <div
              className={`h-full transition-all duration-500 ${
                yearlyData.yearCollectionRate >= 80 ? 'bg-emerald-500' : yearlyData.yearCollectionRate >= 50 ? 'bg-amber-500' : 'bg-rose-500'
              }`}
              style={{ width: `${yearlyData.yearCollectionRate}%` }}
            />
          </div>
        </div>
      </div>

      {/* SVG Collection Bar Chart */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-card">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-extrabold text-sm text-slate-900 flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-indigo-600" />
            <span>{language === 'gu' ? 'માસિક વસૂલાત ચાર્ટ' : 'Monthly Collection Trend'}</span>
          </h3>
          <div className="flex items-center gap-3 text-[10px] font-bold text-slate-600">
            <div className="flex items-center gap-1">
              <span className="w-2.5 h-2.5 rounded-xs bg-slate-200 inline-block" />
              <span>{language === 'gu' ? 'અપેક્ષિત' : 'Expected'}</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="w-2.5 h-2.5 rounded-xs bg-emerald-500 inline-block" />
              <span>{language === 'gu' ? 'વસૂલ' : 'Collected'}</span>
            </div>
          </div>
        </div>

        {/* SVG Visualization */}
        <div className="h-44 flex items-end justify-between gap-1 sm:gap-2 px-1 pt-6">
          {yearlyData.months.map((m) => {
            const expectedHeightPercent = Math.min(100, Math.round((m.demand / yearlyData.maxVal) * 100));
            const collectedHeightPercent = Math.min(100, Math.round((m.collected / yearlyData.maxVal) * 100));

            return (
              <div
                key={m.monthIndex}
                className="flex-1 flex flex-col items-center h-full justify-end group cursor-pointer"
                onClick={() => onSelectMonth?.(selectedYear, m.monthIndex)}
              >
                {/* Tooltip on hover */}
                <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 bg-slate-900 text-white text-[9px] py-1 px-2 rounded pointer-events-none whitespace-nowrap z-10">
                  {m.monthLabel}: ₹{m.collected.toLocaleString('en-IN')} / ₹{m.demand.toLocaleString('en-IN')} ({m.collectionRate}%)
                </div>

                {/* Bars */}
                <div className="w-full max-w-[28px] flex items-end justify-center gap-0.5 h-32 relative">
                  {/* Expected Bar */}
                  <div
                    className="w-1/2 bg-slate-200 rounded-t-xs transition-all duration-300"
                    style={{ height: `${Math.max(4, expectedHeightPercent)}%` }}
                  />
                  {/* Collected Bar */}
                  <div
                    className={`w-1/2 rounded-t-xs transition-all duration-300 ${
                      m.collected >= m.demand && m.demand > 0
                        ? 'bg-emerald-500'
                        : m.collected > 0
                        ? 'bg-emerald-400'
                        : 'bg-slate-300'
                    }`}
                    style={{ height: `${Math.max(4, collectedHeightPercent)}%` }}
                  />
                </div>

                {/* Month Name */}
                <span className="text-[10px] font-bold text-slate-500 mt-2 truncate w-full text-center">
                  {m.monthLabel.slice(0, 3)}
                </span>
              </div>
            );
          })}
        </div>
      </div>

      {/* 12-Month Detailed Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-card overflow-hidden">
        <div className="p-4 border-b border-slate-100 flex items-center justify-between">
          <h3 className="font-extrabold text-sm text-slate-900 flex items-center gap-2">
            <Calendar className="w-4 h-4 text-slate-500" />
            <span>{language === 'gu' ? '૧૨ મહિનાનું કોષ્ટક' : '12-Month Performance Table'}</span>
          </h3>
          <span className="text-xs text-slate-500 font-bold">
            {selectedYear}
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-slate-600 font-bold uppercase tracking-wider text-[10px]">
                <th className="py-3 px-4">{language === 'gu' ? 'મહિનો' : 'Month'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'અપેક્ષિત' : 'Expected'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'વસૂલ' : 'Collected'}</th>
                <th className="py-3 px-3 text-right">{language === 'gu' ? 'બાકી' : 'Pending'}</th>
                <th className="py-3 px-4 text-center">{language === 'gu' ? 'વસૂલાત દર' : 'Collection %'}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {yearlyData.months.map((m) => (
                <tr
                  key={m.monthIndex}
                  onClick={() => onSelectMonth?.(selectedYear, m.monthIndex)}
                  className="hover:bg-slate-50/80 cursor-pointer transition-colors"
                >
                  <td className="py-3 px-4 font-bold text-slate-900">
                    {m.monthLabel}
                  </td>
                  <td className="py-3 px-3 text-right font-medium text-slate-800">
                    {formatCurrency(m.demand)}
                  </td>
                  <td className="py-3 px-3 text-right font-bold text-emerald-600">
                    {formatCurrency(m.collected)}
                  </td>
                  <td className="py-3 px-3 text-right font-bold text-rose-600">
                    {formatCurrency(m.pending)}
                  </td>
                  <td className="py-3 px-4 text-center">
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-black ${
                      m.collectionRate >= 100
                        ? 'bg-emerald-100 text-emerald-800'
                        : m.collectionRate >= 50
                        ? 'bg-amber-100 text-amber-800'
                        : m.collectionRate > 0
                        ? 'bg-rose-100 text-rose-800'
                        : 'bg-slate-100 text-slate-600'
                    }`}>
                      {m.collectionRate}%
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="bg-slate-50 font-extrabold text-slate-900 border-t-2 border-slate-200">
                <td className="py-3 px-4">
                  {language === 'gu' ? 'વાર્ષિક સરવાળો' : 'Annual Total'}
                </td>
                <td className="py-3 px-3 text-right">{formatCurrency(yearlyData.yearTotalDemand)}</td>
                <td className="py-3 px-3 text-right text-emerald-600">{formatCurrency(yearlyData.yearTotalCollected)}</td>
                <td className="py-3 px-3 text-right text-rose-600">{formatCurrency(yearlyData.yearTotalPending)}</td>
                <td className="py-3 px-4 text-center text-indigo-600">{yearlyData.yearCollectionRate}%</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  );
};
